LootCouncilLocalization = {}

LootCouncilLocalization["ACCEPT"] = "Accept"
LootCouncilLocalization["AGAINST"] = "Against"
LootCouncilLocalization["AWARD"] = "Award Item"
LootCouncilLocalization["BAD_CMD"] = "%s is not a valid command for /ltc"
LootCouncilLocalization["BAD_GUILD_RANK"] = "You must select a valid guild rank"
LootCouncilLocalization["BAD_MANUAL_ADD"] = "Invalid Entry. Correct form: /ltc add (charName) (itemLink)"
LootCouncilLocalization["BAD_SLOT"] = "ERROR!!! You linked an INVALID SLOT and are not in the consideration yet for %s. Please re-link!"
LootCouncilLocalization["CANCEL"] = "Cancel"
LootCouncilLocalization["CLEAR_SELECTION"] = "Clear Selection"
LootCouncilLocalization["CLOSE"] = "Close"
LootCouncilLocalization["CMD_ADD"] = " - add (name) (itemlink) - manuall adds a player to the consideration"
LootCouncilLocalization["CMD_CONFIG"] = " - config - shows the main options window"
LootCouncilLocalization["CMD_END"] = " - end - attempts to end a loot council session"
LootCouncilLocalization["CMD_HIDE"] = " - hide - hide the main frame"
LootCouncilLocalization["CMD_MAIN"] = "LOOT COUNCIL COMMANDS:"
LootCouncilLocalization["CMD_PREFIX"] = "prefix: /ltc"
LootCouncilLocalization["CMD_RANK"] = " - rank - shows the frame for setting the guild council ranks"
LootCouncilLocalization["CMD_SHOW"] = " - show - shows the main frame"
LootCouncilLocalization["CMD_START"] = " - start (item) - attempts to start a loot council session"
LootCouncilLocalization["CMD_TEST"] = " - test - opens the test frame"
LootCouncilLocalization["CMD_RESET"] = " - reset - resets the main frame position"
LootCouncilLocalization["CMD_CHANNEL"] = " - channel - sets the main communication channel"
LootCouncilLocalization["CONFIRM_AWARD"] = "Are you sure you want to award %s to %s?"
LootCouncilLocalization["CONFIRM_END"] = "Are you sure you want to end this loot council session?"
LootCouncilLocalization["CONFIRM_END_SESSION"] = "Confirm Ending Session:"
LootCouncilLocalization["CURRENT_COUNCIL"] = "Current Council:"
LootCouncilLocalization["CURRENT_ITEM"] = "Current Item:"
LootCouncilLocalization["DISENCHANT"] = "Disenchant Item"
LootCouncilLocalization["END_FIRED"] = "--------------ENDED--------------"
LootCouncilLocalization["END_SESSION"] = "End Session"
LootCouncilLocalization["FAILED_START_NO_LINK"] = "Correct usage: /ltc start (itemlink)"
LootCouncilLocalization["FAILED_START_NO_VALID_LINK"] = "FAILED TO START - Didn't get item link"
LootCouncilLocalization["FOR"] = "For"
LootCouncilLocalization["GUILD_RANK"] = "Guild Rank"
LootCouncilLocalization["ITEM_LEVEL"] = "Item Lvl:"
LootCouncilLocalization["LINK_GUILD"] = "Allow links through guild chat:"
LootCouncilLocalization["LINK_OFFICERS"] = "Allow links through officer chat:"
LootCouncilLocalization["LINK_RAID"] = "Allow links through raid chat:"
LootCouncilLocalization["LINK_WHISPERS"] = "Allow links through whispers:"
LootCouncilLocalization["LOADING"] = "Loading..."
LootCouncilLocalization["LOOTMENU_AWARD"] = "Award Item"
LootCouncilLocalization["LOOTMENU_END"] = "End Current Session"
LootCouncilLocalization["LOOTMENU_ERROR1"] = "ERROR: Could not automatically loot to %s. Try manually looting to them."
LootCouncilLocalization["LOOTMENU_ERROR2"] = "ERROR: Must have a valid player selected and loot window open."
LootCouncilLocalization["LOOTMENU_ERROR3"] = "Error awarding item. Please try again."
LootCouncilLocalization["LOOTMENU_START"] = "Start New Session"
LootCouncilLocalization["LOOTMENU_DE"] = "Disenchant"
LootCouncilLocalization["MAIN_FRAME_SCALE"] = "Main Frame Scale:"
LootCouncilLocalization["MASTER_LOOT_INTEGRATE"] = "Master Loot Integration:"
LootCouncilLocalization["MIN_RANK"] = "Minimum rank to participate in Loot Council:"
LootCouncilLocalization["NEW_ENTRY"] = "You are now being considered for %s"
LootCouncilLocalization["NEW_ENTRY_SPEC"] = "You are now being %s SPEC considered for %s"
LootCouncilLocalization["NONE"] = "None"
LootCouncilLocalization["NOSTART_1"] = "You cannot start a new Loot Council Session."
LootCouncilLocalization["NOSTART_NOT_GM"] = "You must be in a Raid or the Guild Leader to start a new Loot Council Session"
LootCouncilLocalization["NOSTART_NOT_RAIDASSIST"] = "You must be a Raid Assistant to start a new Loot Council Session"
LootCouncilLocalization["OUTDATED"] = "YOUR LOOT COUNCIL VERSION IS OUTDATED. Please upgrade to version %s!!!"
LootCouncilLocalization["PRIVATE_VOTING"] = "Private Voting:"
LootCouncilLocalization["SPLIT_RAIDS"] = "One LC per Raid:"
LootCouncilLocalization["RAIDER"] = "Raider"
LootCouncilLocalization["REMOVE_FROM_CONSIDERATION"] = "Remove From Consideration"
LootCouncilLocalization["SELECTION"] = "Selection:"
LootCouncilLocalization["SELF_VOTE"] = "Council members can vote for self:"
LootCouncilLocalization["SINGLE_VOTE"] = "Single Vote Mode:"
LootCouncilLocalization["SPEC"] = "Spec"
LootCouncilLocalization["SPEC_INFO"] = "Display Main/Off Spec Information:"
LootCouncilLocalization["START_FIRED"] = "--------------STARTED--------------"
LootCouncilLocalization["START_MSG_PULSE1"] = "%s now under consideration!"
LootCouncilLocalization["START_MSG_PULSE2"] = "If you want %s, whisper %s your current item. Use the format \"[item] keyword\". Keywords are: off, 2set, 4set, bis and xmog for special consideration."
--							if spec == "M" then
--								fullSpec = "MAIN";
--							elseif spec == "OFF" then
--								fullSpec = "OFFSPEC";
--							elseif spec == "2SET" then
--								fullSpec = "BONUS SET (2 parts)";
--							elseif spec == "4SET" then
--								fullSpec = "BONUS SET (4 parts)";
--							elseif spec == "XMOG" then
--								fullSpec = "TRANSMOG";
--							elseif spec =="BIS" then
--								fullSpec = "BiS";
--							else
--								fullSpec = "UNKNOWN";
--							end

LootCouncilLocalization["START_WHILE_GOING1"] = "%s tried to start a new consideration"
LootCouncilLocalization["START_WHILE_GOING2"] = "but we already had one running!"
LootCouncilLocalization["START_WHILE_SESSION1"] = "Could not start a new consideration"
LootCouncilLocalization["START_WHILE_SESSION2"] = "Already running for %s"
LootCouncilLocalization["START_WHILE_SESSION2_NOLINK"] = "Already running a loot council session."
LootCouncilLocalization["SUGGEST_ABORT"] = "%s has suggested you abort this loot council session."
LootCouncilLocalization["TOO_LOW_RANK"] = "%s tried to start a new loot council session had insufficient privileges."
LootCouncilLocalization["TOTAL_VOTES"] = "Total Votes (+/-)"
LootCouncilLocalization["UPDATE_PROCESSED"] = "Received update in consideration for %s"
LootCouncilLocalization["UPDATE_PROCESSED_FEEDBACK1"] = " - Your current item: "
LootCouncilLocalization["UPDATE_PROCESSED_FEEDBACK2"] = " - Your current items: "
LootCouncilLocalization["UPDATE_PROCESSED_SPEC"] = "received update in %s SPEC consideration for %s"
LootCouncilLocalization["UPGRADED_ITEM"] = "Upgraded Item"
LootCouncilLocalization["VOTES_AGAINST"] = "Votes Against:"
LootCouncilLocalization["VOTES_FOR"] = "Votes For:"
LootCouncilLocalization["YOUR_VOTE"] = "Your Vote"
LootCouncilLocalization["NO_VOTES_FOR"] = "No votes for"
LootCouncilLocalization["NO_VOTES_AGAINST"] = "No votes against"
LootCouncilLocalization["RUN_TEST"] = "Test Council";
LootCouncilLocalization["RESYNC"] = "Resync";
LootCouncilLocalization["LOW_RANK"] = "%s - (Low Rank)\n";
LootCouncilLocalization["INVALID_INIT"] = "%s - (Invalid Initiator)\n";
LootCouncilLocalization["INFO_APPROVED1"] = "Approved Council";
LootCouncilLocalization["INFO_APPROVED2"] = "These members will be on the council once you start a new session";
LootCouncilLocalization["INFO_LOWRANK1"] = "Low Rank";
LootCouncilLocalization["INFO_LOWRANK2"] = "These members are below YOUR configured rank";
LootCouncilLocalization["INFO_INVALIDINIT1"] = "Invalid Initiator";
LootCouncilLocalization["INFO_INVALIDINIT2"] = "These members have configured your rank too low";
LootCouncilLocalization["INFO_NOTSHOWN1"] = "Not Shown";
LootCouncilLocalization["INFO_NOTSHOWN2"] = "If someone does not appear on either list, the mod is either disabled or outdated";
LootCouncilLocalization["ENCHANTERS"] = "Enchanters";
LootCouncilLocalization["CHANNEL_NOT_JOINED"] = "Default channel not changed - Only allows channels that you have joined";
LootCouncilLocalization["MAIN_CHANNEL"] = "Current default communication channel";